spring:
  application:
    name: openai-api-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
          jwk-set-uri: ${COGNITO_JWK_SET_URI:${COGNITO_ISSUER_URI}/.well-known/jwks.json}
