spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: openai-api-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_j7SMcRyWv
          jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_j7SMcRyWv/.well-known/jwks.json
aws:
  cognito:
    userPoolId: eu-central-1_j7SMcRyWv
    clientId: l6p54peadaqdhlfahb2fvega4
    clientSecret: 1ipc3qs63k7o9f6piieibbm1cdpak6c6gmhshbolc612m5jk1579
    region: eu-central-1
